name: 'Robot Framework Report - by Bessa'
description: 'Report your Robot Framework Tests in your PRs'
inputs:
  report-artifact-name:  
    description: 'Your result reports artifact'
    required: true
  access-token:  
    description: 'Github Access Token'
    required: true
  repo-owner: 
    description: 'Repository Owner'
    required: true
  repository: 
    description: 'Repository'
    required: true  
  bucket-gcp-name: 
    description: 'Bucket GCP Name'
outputs:
  robot-result: # id da saída
    description: 'Robot Results'
runs:
  using: 'node12'
  main: 'dist/index.js'