name: 'Robot Framework Report - by Bessa'
description: 'Report your Robot Framework Tests in your PRs'
inputs:
  report-artifact-name:  
    description: 'Your result reports artifact'
    required: true
  access-token:  
    description: 'Github Access Token'
    required: true
  repo-owner: 
    description: 'Repository Owner'
    required: true
  sha: 
    description: 'Commit SHA ID'
    required: true
  repository: 
    description: 'Repository'
    required: true  
outputs:
  time: # id da saída
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'index.js'